In [1]:
import numpy as np

In [5]:
# Example of a Full-rank system.
A = np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]])
u, s, v_t = np.linalg.svd(A, full_matrices=True)
v = v_t.T
print("U:")
print(u)
print("Singular Values:")
print(s)
print("V:")
print(v)

U:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Singular Vaulues:
[2. 2. 2.]
V:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# Example of an over-constrained system.
A = np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2], [2, 0, 0]])
u, s, v_t = np.linalg.svd(A, full_matrices=True)
v = v_t.T
print("U:")
print(u)
print("Singular Values:")
print(s)
print("V:")
print(v)

U:
[[-0.70710678  0.          0.         -0.70710678]
 [ 0.          0.          1.          0.        ]
 [ 0.          1.          0.          0.        ]
 [-0.70710678  0.          0.          0.70710678]]
Singular Values:
[2.82842712 2.         2.        ]
V:
[[-1.  0.  0.]
 [-0.  0.  1.]
 [-0.  1.  0.]]


In [9]:
# Example of under-constrained system.
A = np.array([[2, 0, 0], [0, 2, 0]])
u, s, v_t = np.linalg.svd(A, full_matrices=True)
v = v_t.T
print("U:")
print(u)
print("Singular Values:")
print(s)
print("V:")
print(v)

U:
[[1. 0.]
 [0. 1.]]
Singular Values:
[2. 2.]
V:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
